# Generated by Django 5.2.4 on 2025-07-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_github_link_project_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_token', models.CharField(blank=True, help_text='GitHub Personal Access Token for higher rate limits', max_length=100)),
                ('last_rate_limit_reset', models.DateTimeField(blank=True, null=True)),
                ('requests_remaining', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'GitHub API Configuration',
                'verbose_name_plural': 'GitHub API Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('full-stack', 'Full-Stack'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('data-viz', 'Data Visualization'), ('ai-ml', 'AI/ML'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Main challenges faced'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show as featured project'),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of key features'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='github_data_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_username',
            field=models.CharField(blank=True, help_text="Your GitHub username (e.g., 'iBarzha')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='learning',
            field=models.TextField(blank=True, help_text='What you learned from this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_name',
            field=models.CharField(blank=True, help_text="GitHub repository name (e.g., 'chnu-db', 'films-library')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('production', 'Production'), ('development', 'Active Development'), ('completed', 'Completed'), ('archived', 'Archived')], default='development', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
