# Generated by Django 5.2.4 on 2025-07-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_githubapiconfig_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['language', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English 🇺🇸'), ('uk', 'Ukrainian 🇺🇦'), ('pl', 'Polish 🇵🇱')], default='en', help_text='Which language version is this project for?', max_length=10),
        ),
    ]
